# This file was generated by GoReleaser. DO NOT EDIT.
cask "choragos" do
  version "0.18.1"

  on_macos do
    on_intel do
      sha256 "4ad5d2c53232af1b6916528055c363791ab45fc566dbb530b68974bd65be801b"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "da97b37f00f9b1beb80fb3cfbfe53d025a55e8258bcc73bc1f58305cd10b72b8"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "dac0b0827e0a8a7fa60b63bdf453ac2e34ee75b3ff71958d15b458aae6c2991d"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ce6d7ef21bf85600d1b92613a622f3ef060eccf8c2e608867dc11fb60a58e12b"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_linux_arm64.tar.gz"
    end
  end

  name "choragos"
  desc "Secure multi-agent development orchestrator TUI"
  homepage "https://github.com/sphragis-oss/choragos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "choragos"
  manpage "manpages/choragos-attach.1"
  manpage "manpages/choragos-checkpoints-prune.1"
  manpage "manpages/choragos-checkpoints.1"
  manpage "manpages/choragos-delegate.1"
  manpage "manpages/choragos-doctor.1"
  manpage "manpages/choragos-init.1"
  manpage "manpages/choragos-kill.1"
  manpage "manpages/choragos-ls.1"
  manpage "manpages/choragos-reload.1"
  manpage "manpages/choragos-report.1"
  manpage "manpages/choragos-rollback.1"
  manpage "manpages/choragos-roster-add.1"
  manpage "manpages/choragos-roster.1"
  manpage "manpages/choragos-serve.1"
  manpage "manpages/choragos-version.1"
  manpage "manpages/choragos-work-done.1"
  manpage "manpages/choragos.1"
  bash_completion "completions/choragos.bash"
  fish_completion "completions/choragos.fish"
  zsh_completion "completions/_choragos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/choragos"]
    end
  end

  # No zap stanza required

end
