# This file was generated by GoReleaser. DO NOT EDIT.
cask "choragos" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "6c2f4b0e61689dfe6d1cee8fa64dd581ef7941c2d9f64ae33246370c7d775ab0"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "715c601415c4e1421f23dcf8cdf0553e8094fa9dac6160fae2bb48f7f185b65f"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0167f4aa39d2432fa03ce14371b91c1d2e18db7dd0330d4e43d26d806f3892d"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66c5312af15940047c8c6b3f83b1073f3913648590bc6e2efa2de7e9caaf1a7a"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_linux_arm64.tar.gz"
    end
  end

  name "choragos"
  desc "Secure multi-agent development orchestrator TUI"
  homepage "https://github.com/sphragis-oss/choragos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "choragos"
  manpage "manpages/choragos-attach.1"
  manpage "manpages/choragos-checkpoints-prune.1"
  manpage "manpages/choragos-checkpoints.1"
  manpage "manpages/choragos-delegate.1"
  manpage "manpages/choragos-doctor.1"
  manpage "manpages/choragos-init.1"
  manpage "manpages/choragos-kill.1"
  manpage "manpages/choragos-ls.1"
  manpage "manpages/choragos-reload.1"
  manpage "manpages/choragos-report.1"
  manpage "manpages/choragos-rollback.1"
  manpage "manpages/choragos-roster-add.1"
  manpage "manpages/choragos-roster.1"
  manpage "manpages/choragos-serve.1"
  manpage "manpages/choragos-version.1"
  manpage "manpages/choragos-work-done.1"
  manpage "manpages/choragos.1"
  bash_completion "completions/choragos.bash"
  fish_completion "completions/choragos.fish"
  zsh_completion "completions/_choragos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/choragos"]
    end
  end

  # No zap stanza required

end
