# This file was generated by GoReleaser. DO NOT EDIT.
cask "choragos" do
  version "0.17.0"

  on_macos do
    on_intel do
      sha256 "71ccc2cdafa628d7b57cc36128b8c4c1fc966b6964409b33b94ff367c5185d55"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "79e89b616ddaf5ee71e8a2fd9715dd9d281512a7e1c3780a0f427171d9d027d2"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c191b146f4f9b5e6e2f4de141980aca563dd46fdfc4c7a0cfe040927e70e977a"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1f339a0d8682e7154b0c3db50755dfd4d09d975883c9a841fa9e301a9661581"
      url "https://github.com/sphragis-oss/choragos/releases/download/v#{version}/choragos_linux_arm64.tar.gz"
    end
  end

  name "choragos"
  desc "Secure multi-agent development orchestrator TUI"
  homepage "https://github.com/sphragis-oss/choragos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "choragos"
  manpage "manpages/choragos-attach.1"
  manpage "manpages/choragos-checkpoints-prune.1"
  manpage "manpages/choragos-checkpoints.1"
  manpage "manpages/choragos-delegate.1"
  manpage "manpages/choragos-doctor.1"
  manpage "manpages/choragos-init.1"
  manpage "manpages/choragos-kill.1"
  manpage "manpages/choragos-ls.1"
  manpage "manpages/choragos-reload.1"
  manpage "manpages/choragos-report.1"
  manpage "manpages/choragos-rollback.1"
  manpage "manpages/choragos-roster-add.1"
  manpage "manpages/choragos-roster.1"
  manpage "manpages/choragos-serve.1"
  manpage "manpages/choragos-version.1"
  manpage "manpages/choragos-work-done.1"
  manpage "manpages/choragos.1"
  bash_completion "completions/choragos.bash"
  fish_completion "completions/choragos.fish"
  zsh_completion "completions/_choragos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/choragos"]
    end
  end

  # No zap stanza required

end
