# This file was generated by GoReleaser. DO NOT EDIT.
cask "isthmos" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f4018d98abec2a7dca9be6a076c6e9201da3636a2b6d671719ffa9f73dc77154"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ff12c8cecbccf108145f890185e2adc61002878124b116005d7f916336fed8a"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ae3dd07fba998526e6947d9edb311ff57bd460bca026e67cb2c9302976ef676"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c2f6687ff5a2e45a0501c59a309804c76ece4c840fe8d707c1ed711671ec43b9"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_linux_arm64.tar.gz"
    end
  end

  name "isthmos"
  desc "Local context-compression layer for agent tool outputs"
  homepage "https://github.com/sphragis-oss/isthmos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "isthmos"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/isthmos"]
    end
  end

  # No zap stanza required

end
