# This file was generated by GoReleaser. DO NOT EDIT.
cask "isthmos" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "bcf1d51f4f40f1f8769ad9fae4cca81d81753a411644feddc4886df3842ad7fb"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee47b59d1266a8f0ff6191c2b7e931eb300cf9422a202d49d97d47d5d5deac98"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "28645200650d2dc874f56b01f58fa8e143a900a7eb80d3d3173c6fb2c741d369"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "42110e31dc353137123093d61a52c7970922bb5d227b940c344c276feabef5a6"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_linux_arm64.tar.gz"
    end
  end

  name "isthmos"
  desc "Local context-compression layer for agent tool outputs"
  homepage "https://github.com/sphragis-oss/isthmos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "isthmos"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/isthmos"]
    end
  end

  # No zap stanza required

end
