# This file was generated by GoReleaser. DO NOT EDIT.
cask "isthmos" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/isthmos"]
    end
  end

  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "15a9fba9ef27a5d48cad08276852cb3db4a2c1f687cad0c29a4cc74afd9d34b8"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f1c1b1c542518c1073464d9629e0ec81816a72c7833002cf940e68475a62c3c2"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5029679185c1a6815f355b2ecbd65dc9a8710df5008ef33199117d9b993511d5"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "77f1083ce7164d5cebd525ab187ddd8d1930432435771c6073b787c51d5c0f8e"
      url "https://github.com/sphragis-oss/isthmos/releases/download/v#{version}/isthmos_linux_amd64.tar.gz"
    end
  end

  name "isthmos"
  desc "Local context-compression layer for agent tool outputs"
  homepage "https://github.com/sphragis-oss/isthmos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "isthmos"

  # No zap stanza required
end
