# This file was generated by GoReleaser. DO NOT EDIT.
cask "sphragis" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "6d685823f9d99c1a50c8119d384d6b9d847251c5fe83bc741a1d990b30877a9b"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6130441688e8d771907d1323b8982bec019a41f0a843fee14a60fe465f825b6c"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a2742959d46d4d73974d833f0bda8f5449444c12e65a55bb083afa50f878cf4"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7490ef306dd41b8a62aa7f5b2cd2a1761303daace9a83143b57a8f8a797054ca"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_linux_arm64.tar.gz"
    end
  end

  name "sphragis"
  desc "EU AI Act compliance gateway: local PII redaction and a tamper-evident audit log"
  homepage "https://sphragis.eu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sphragis"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sphragis"]
    end
  end

  # No zap stanza required

end
