# This file was generated by GoReleaser. DO NOT EDIT.
cask "sphragis" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "e20d579d8a5157a8fcdea0ce8e2d8d25eff8dcbd46d18cb95cb35236e6e391c0"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3fbebf4c33c4db8d3207da463f9641fd71e230362ff3b42deeea902c225ab6ed"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6baa2cb8723b77a657ed6cc829efda912349cb3d913a756832fcd4d4291c41fb"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b12474f03fb5356b0af0bbb6b8002adebbd049ecabf499796fb563d346deee93"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_linux_arm64.tar.gz"
    end
  end

  name "sphragis"
  desc "EU AI Act compliance gateway: local PII redaction and a tamper-evident audit log"
  homepage "https://sphragis.eu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sphragis"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/sphragis"]
    end
  end

  # No zap stanza required

end
