# This file was generated by GoReleaser. DO NOT EDIT.
cask "sphragis" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "9686ef91612723ad5c2ae4d5253737c47289b3c34c740137fb604eb5540bcc93"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a62c07bf7ae8349534127f9642ebcd89f432b4dbbf4a2f5dd4ae1a7964d4c173"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "25453ee06520d001b03ae4e1329dbb6266f9e074b9bd52cea708713bbe92c613"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a00929eba84c33f00e25debb5727731f90e22e394f0c13270768af8d0b00fdd4"
      url "https://github.com/sphragis-oss/sphragis/releases/download/v#{version}/sphragis_linux_arm64.tar.gz"
    end
  end

  name "sphragis"
  desc "EU AI Act compliance gateway: local PII redaction and a tamper-evident audit log"
  homepage "https://sphragis.eu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sphragis"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sphragis"]
    end
  end

  # No zap stanza required

end
